version: '3.8'

services:
  # Serviço do Banco de Dados MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - internal

  # Serviço do Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sales_api
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    restart: always
    networks:
      - internal
      - external

  # Serviço do Frontend React (usando a imagem Nginx de produção)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sales_ui
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
  external:
    driver: bridge

volumes:
  mongo_data:

